version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.18.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: npm publish

experimental:
  notify:
    branches:
      only:
        - master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: LE
      - publish:
          context: LE
          requires:
            - build
          filters:
            branches:
              only: master
